on: push
name: winner app changes
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: game.44shop.ir
          protocol: ftp
          port: 21
          username: shopir13
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /game/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            vendor/**
            server.php
